name: Bug Report
description: This is a bug report
title: "[Bug]: "
labels: ["Type - Bug :lady_beetle:", "Triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! If is is urgent add the urgent label to the Issue
  - type: dropdown
    id: Product
    attributes:
      label: Product
      description: Which Product is this apaort of?
      options:
        - POMA
        - POM (Wrong Repository)
        - POH (Wrong Repository)
        - Gateway
        - Connecting Shop (Wrong Repository)
        - Connecting Prodrisk (Wrong Repository)
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: Which Product version [Other versions should be in Additional info]
      placeholder: v0.0.0
    validations:
      required: false
  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: What is the severity of the bug?
      options:
        - Critical
        - Major
        - Minor
    validations:
      required: true
  - type: input
    id: customer
    attributes:
      label: Customer
      description: Which customer is this impacting (Leave empty if none or unknown)
      placeholder: Customer
    validations:
      required: false
  - type: input
    id: Enviorment
    attributes:
      label: Enviorment
      description: In what enviorment did this happen in?
      placeholder: Enviorment
    validations:
      required: false
  - type: input
    id: Database
    attributes:
      label: Database
      description: In what enviorment did this happen in?
      placeholder: Database
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: textarea
    id: additional-info
    attributes:
      label: Additional Info
      description: Any additional info?
      placeholder: Any details!
    validations:
      required: false
