name: Feature
description: File a bug report
title: "[Bug]: "
labels: ["Type - Bug :lady_beetle:", "Triage", ""]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: checkboxes
    id: SupportIssue
    attributes:
      label: SupportIssue
      description: Is this a support Issue
      options:
        - label: Is this a support Issue
          required: false
  - type: input
    id: Version
    description: Which version does it occur for
    attributes:
      label: Version
      placeholder: v.0.0.0
    validations:
      required: false
  - type: input
    id: customer
    attributes:
      label: Customer
      description: Which customer is this impacting (Leave empty if none or unknown)
      placeholder: Customer
    validations:
      required: false
  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: What is the severity of the bug?
      options:
        - Critical
        - Major
        - Minor
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Reproduction steps
      description: "How do you trigger this bug? Please walk us through it step by step."
      value: |
        1.
        2.
        3.
        ...
      render: bash
    validations:
      required: true
  - type: checkboxes
    id: 
    attributes:
      label: Urgent
      description: Is this a urgent Issue
      options:
        - label: Is this a urgent Issue
          required: false
