name: Bug fix
description: File a bug report
title: "[Bug]: "
labels: ["Type - Bug :lady_beetle:", "Triage", ""]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: dropdown
    id: Product
    attributes:
      label: Product
      description: Which Product is this apaort of?
      options:
        - POMA
        - POM (wrong repo)
        - POH (wrong repo)
        - Gateway (wrong repo)
        - Connecting Shop (wrong repo)
        - Connecting Prodrisk (wrong repo)
    validations:
      required: true
  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: What is the severity of the bug?
      options:
        - Critical
        - Major
        - Minor
    validations:
      required: true
  - type: checkboxes
    id: Urgent
    attributes:
      label: Urgent
      options:
        - label: Is this a urgent Issue
          required: false
  - type: checkboxes
    id: SupportIssue
    attributes:
      label: Support Issue
      options:
        - label: Is this issue generated by support
          required: false
  - type: input
    id: customer
    attributes:
      label: Customer
      description: Which customer is this impacting (Leave empty if none or unknown)
      placeholder: Customer
    validations:
      required: false
  - type: input
    id: Enviorment
    attributes:
      label: Enviorment
      description: In what enviorment did this happen in?
      placeholder: Enviorment
    validations:
      required: false
  - type: input
    id: Enviorment
    attributes:
      label: Enviorment
      description: In what enviorment did this happen in?
      placeholder: Enviorment
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
