name: "Issue - Labled: Transfer"

on:
  issues:
    types:
      - labeled

env:
  BASE_LABEL: Product - POMA

jobs:
  transfer_issue:
    name: transfer issue
#    if: "${{ contains(github.event.label.name, 'Product') }}"
    runs-on: ubuntu-latest
    steps:
    - name: Transfer ${{ env.LABEL }}
      if: ${{ github.event.label.name == env.LABEL && !contains(github.issue.labels.*.name,  env.BASE_LABEL) }}
      uses: lando/transfer-issue-action@v2
      with:
        token: ${{ secrets.OPT_GH_TOKEN }}
        router: ${{ env.LABEL}}:${{ env.REPO }}
        debug: true
        create_stub: true
      env:
        LABEL: Product - POM
        REPO: TestRepo

    - name: Transfer ${{ env.LABEL }}
      if: ${{ github.event.label.name == env.LABEL && !contains(github.issue.labels.*.name,  env.BASE_LABEL) }}
      uses: lando/transfer-issue-action@v2
      with:
        token: ${{ secrets.OPT_GH_TOKEN }}
        router: ${{ env.LABEL}}:${{ env.REPO }}
        debug: true
        create_stub: true
      env:
        LABEL: Product - POH
        REPO: TestRepo

    - name: Transfer ${{ env.LABEL }}
      if: ${{ github.event.label.name == env.LABEL && !contains(github.issue.labels.*.name,  env.BASE_LABEL) }}
      uses: lando/transfer-issue-action@v2
      with:
        token: ${{ secrets.OPT_GH_TOKEN }}
        router: ${{ env.LABEL}}:${{ env.REPO }}
        debug: true
        create_stub: true
      env:
        LABEL: Product - Connecting Shop
        REPO: TestRepo

    - name: Transfer ${{ env.LABEL }}
      if: ${{ github.event.label.name == env.LABEL && !contains(github.issue.labels.*.name,  env.BASE_LABEL) }}
      uses: lando/transfer-issue-action@v2
      with:
        token: ${{ secrets.OPT_GH_TOKEN }}
        router: ${{ env.LABEL}}:${{ env.REPO }}
        debug: true
        create_stub: true
      env:
        LABEL: Product - Optimal Log
        REPO: TestRepo
