name: "Issue - Labled: Transfer"

on:
  issues:
    types:
      - labeled

env:
  BASE_LABEL: Product - POMA
  Protected

jobs:
  transfer_issue:
    name: transfer issue
    if: ${{ contains(github.event.label.name, 'Product') }}
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        include:
          - LABEL: "Product - POMA"
            REPO: "labelOnPRReview"
          - LABEL: "Product - POM" 
            REPO: "TestRepo"
          - LABEL: "Product - POH"
            REPO: "TestRepo"
          - LABEL: "Product - Connecting Shop"
            REPO: "TestRepo"
          - LABEL: "Product - Connecting Prodrisk"
            REPO: "TestRepo"
          - LABEL: "Product - Optimal Log"
            REPO: "TestRepo"

    steps:
    - name: Check Protection
      run: |
        PROTECTED = ${{ matrix.Protected }}
        PROTECTED += ${{ env.Protected }}
        CHECK += ${{ github.event.issue.labels.*.name}} 
        echo $CHECK
        STOP = "false"
        for check in ${PROTECTED[*]}
        do
          for against in ${CHECK[*]}
            if [[ $check == $against]]
              STOP = "true"
            fi
          done
        done
        echo ::set-output name=stop::${STOP}

      id: check
      shell: bash
    - name: Transfer ${{ env.LABEL }}
      if: ${{ steps.check.outputs.stop != true && github.event.label.name == env.LABEL && github.repository != 'github.repository_owner/matrix.REPO' && !contains(github.event.issue.labels.*.name,  env.BASE_LABEL)}}
      uses: lando/transfer-issue-action@v2
      with:
        token: ${{ secrets.OPT_GH_TOKEN }}
        router: ${{ matrix.LABEL}}:${{ matrix.REPO }}
        debug: true
        create_stub: true