name: "Issue - Labled: Transfer"

on:
  issues:
    types:
      - labeled

env:
  PROTECTED: ("Product - POMA")

jobs:
  transfer_issue:
    name: transfer issue
    if: ${{ contains(github.event.label.name, 'Product') }}
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        include:
          - LABEL: "Product - POMA"
            REPO: "labelOnPRReview"
            PROTECTED: "('Product - Gateway')"
          - LABEL: "Product - Gateway"
            REPO: "TestRepo"
            PROTECTED: "('Product - POMA')"
          - LABEL: "Product - POM" 
            REPO: "TestRepo"
            PROTECTED: "()"
          - LABEL: "Product - POH"
            REPO: "TestRepo"
            PROTECTED: "()"
          - LABEL: "Product - Connecting Shop"
            REPO: "TestRepo"
            PROTECTED: "()"
          - LABEL: "Product - Connecting Prodrisk"
            REPO: "TestRepo"
            PROTECTED: "()"
          - LABEL: "Product - Optimal Log"
            REPO: "TestRepo"
            PROTECTED: "()"

    steps:
    - name: Check Protection
      run: |
        PROTECTED=${{ matrix.PROTECTED }}
        PROTECTED+=${{ env.PROTECTED }}
        CHECK+=${{ fromJSON(github.event.issue.labels.*.name) }} 
        echo $CHECK
        STOP = "false"
        for check in ${PROTECTED[*]}
        do
          for against in ${CHECK[*]}
            if [[ $check == $against]]
              STOP = "true"
            fi
          done
        done
        echo ::set-output name=stop::${STOP}

      id: check
      shell: bash
    - name: Transfer ${{ env.LABEL }}
      if: ${{ steps.check.outputs.stop != true && github.event.label.name == env.LABEL && github.repository != 'github.repository_owner/matrix.REPO' }}
      uses: lando/transfer-issue-action@v2
      with:
        token: ${{ secrets.OPT_GH_TOKEN }}
        router: ${{ matrix.LABEL}}:${{ matrix.REPO }}
        debug: true
        create_stub: true