name: "Issue - Labled: Transfer"

on:
  issues:
    types:
      - labeled

env:
  PROTECTED: 

jobs:
  transfer_issue:
    name: transfer issue
    if: ${{ contains(github.event.label.name, 'Product') }}
    runs-on: ubuntu-latest
    steps:

## Check if any labels are protected

    - name: Check Protection
      id: protect
      uses: ChristofferDahlen/Multi-Regex-Match@v1.0
      with:
        input: "${{toJSON(github.event.issue.labels.*.name) }}"
        json_match: '{ "\\bProduct - POMA\\b" : "true" }'

## Match label with repo
    - name: Match Label
      if: steps.protect.outputs.result != true && github.repository != 'github.repository_owner/matrix.REPO' 
      id: match
      uses: ChristofferDahlen/Multi-Regex-Match@v1.0
      with:
        input: "${{ github.event.label.name }}"
        json_match: '{
          "Product - POMA\\b" : "labelOnPRReview",
          "Product - Gateway\\b" : "testRepo",
          "Product - POM\\b" : "testRepo",
          "Product - POH\\b" : "testRepo",
          "Product - Spotbid\\b" : "false",
          "Product - Connecting Shop\\b" : "testRepo",
          "Product - Prodrisk\\b" : "testRepo",
          "Product - Optimal log\\b" : "testRepo"
        }'

## Check
    - name: Transfer Issue to ${{ steps.match.outputs.result }}
      if: steps.protect.outputs.result != true && steps.match.outputs.result != 'false' && github.repository != '${{ github.repository_owner}}/${{ steps.match.outputs.result }}' 
      uses: christofferDahlen/transfer-issue-action@v3
      with:
        target_repo: ${{ steps.match.outputs.result }}
        token: '${{ secrets.OPT_GH_TOKEN }}'
        debug: true
        create_stub: true
