name: "Issue - Labled: Transfer"

on:
  issues:
    types:
      - labeled

env:
  BASE_LABEL: Product - POMA

jobs:
  transfer_issue:
    name: transfer issue
    if: ${{ contains(github.event.label.name, 'Product') }}
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        include:
          - LABEL: "Product - POMA"
            REPO: "labelOnPRReview"
          - LABEL: "Product - POM" 
            REPO: "TestRepo"
          - LABEL: "Product - POH"
            REPO: "Powel.SmE.Optimal.Hydro"
          - LABEL: "Product - Connecting Shop"
            REPO: "Powel.Optimal.Gateway"
          - LABEL: "Product - Connecting Prodrisk"
            REPO: "Powel.Optimal.Gateway"
          - LABEL: "Product - Optimal Log"
            REPO: "Powel.Optimal.Log"

    steps:
    - name: Get Repo Name
      run: echo ::set-env name=REPOSITORY_NAME::$(echo "$GITHUB_REPOSITORY" | awk -F / '{print $2}')
      shell: bash
    - name: Transfer ${{ env.LABEL }}
      if: ${{ github.event.label.name == env.LABEL && $REPOSITORY_NAME != matrix.REPO && !contains(github.event.issue.labels.*.name,  env.BASE_LABEL)}}
      uses: lando/transfer-issue-action@v2
      with:
        token: ${{ secrets.OPT_GH_TOKEN }}
        router: ${{ matrix.LABEL}}:${{ matrix.REPO }}
        debug: true
        create_stub: true