
name: "Issue: Comment - labeling"

on:
  issue_comment:
    types: [created]
    # This is for both PR and Issues


jobs:
  labeling-on-comment:
    if: ${{ !github.event.issue.locked && github.event.issue.state != 'closed' }}
    runs-on: ubuntu-latest
    steps:

    - name: Get Current Issue State
      uses: octokit/request-action@v2.x
      id: get_body
      with:
        route: GET /repos/${{ github.repository}}/issues/${{github.event.issue.number}}      
      env:
        GITHUB_TOKEN: ${{ secrets.OPT_GH_TOKEN }}

    - uses: Amwam/issue-comment-action@v1.3.1
      if: fromJson(steps.get_body.outputs.data).state == 'open'
      with:
        keywords: '["help @"]'
        labels: '["Help Wanted"]'
        github-token: "${{ secrets.GITHUB_TOKEN }}"

    - uses: Amwam/issue-comment-action@v1.3.1
      if: fromJson(steps.get_body.outputs.data).state == 'open'
      with:
        keywords: '["blocking"]'
        labels: '["Blocking :exclamation:"]'
        github-token: "${{ secrets.GITHUB_TOKEN }}"

    - uses: Amwam/issue-comment-action@v1.3.1
      if: fromJson(steps.get_body.outputs.data).state == 'open'
      with:
        keywords: '["blocked by"]'
        labels: '["Blocked :no_entry_sign:"]'
        github-token: "${{ secrets.GITHUB_TOKEN }}"

    - uses: Amwam/issue-comment-action@v1.3.1
      if: fromJson(steps.get_body.outputs.data).state == 'open'
      with:
        keywords: '["Cannot Reproduce"]'
        labels: '["Cannot Reproduce"]'
        github-token: "${{ secrets.GITHUB_TOKEN }}"

    - uses: Amwam/issue-comment-action@v1.3.1
      if: fromJson(steps.get_body.outputs.data).state == 'open'
      with:
        keywords: '["Duplicate of"]'
        labels: '["Duplicate"]'
        github-token: "${{ secrets.GITHUB_TOKEN }}"

    - uses: Amwam/issue-comment-action@v1.3.1
      if: fromJson(steps.get_body.outputs.data).state == 'open'
      with:
        keywords: '["Urgent"]'
        labels: '["Urgent :bangbang:"]'
        github-token: "${{ secrets.GITHUB_TOKEN }}"

