name: "Issue - Labled: Transfer"

on:
  issues:
    types:
      - labeled

env:
  PROTECTED: '{ "\\bProduct - POMA\\b" : "true" }'

jobs:
  transfer_issue:
    name: transfer issue
    if: ${{ contains(github.event.label.name, 'Product') }}
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        include:
          - LABEL: "Product - POMA"
            REPO: "labelOnPRReview"
          - LABEL: "Product - Gateway"
            REPO: "TestRepo"
          - LABEL: "Product - POM" 
            REPO: "TestRepo"
          - LABEL: "Product - POH"
            REPO: "TestRepo"
          - LABEL: "Product - Connecting Shop"
            REPO: "TestRepo"
          - LABEL: "Product - Connecting Prodrisk"
            REPO: "TestRepo"
          - LABEL: "Product - Optimal Log"
            REPO: "TestRepo"

    steps:
    - name: Match body
      if:  github.event.label.name == matrix.LABEL && github.repository != 'github.repository_owner/matrix.REPO'
      id: match
      uses: ChristofferDahlen/Multi-Regex-Match@v1.0
      with:
        input: "${{toJSON(github.event.issue.labels.*.name) }}"
        json_match: ${{ env.PROTECTED }}
    - name: Transfer ${{ env.LABEL }}
      if: ${{ steps.match.outputs.result != true && github.event.label.name == matrix.LABEL && github.repository != 'github.repository_owner/matrix.REPO' }}
      uses: lando/transfer-issue-action@v2
      with:
        token: ${{ secrets.OPT_GH_TOKEN }}
        router: ${{ matrix.LABEL}}:${{ matrix.REPO }}
        debug: true
        create_stub: true