
on:
  issues:
    types: [opened, edited, closed, reopened]
  pull_request:
    types: [opened, edited, closed, reopened, synchronize]
  project_card:
    types: [created, moved, deleted]

name: mastermind-Labeling
jobs:
  mastermind-label:
    runs-on: ubuntu-latest
    name: Label issues and pull requests
    steps:
      - uses: Resnovas/label-mastermind@2.1.3
        with:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
