name: Setup new Pull Requests

on:
  pull_request:
    types: [opened]

jobs:
  Handle_Synced_Labels:
    runs-on: ubuntu-latest
    name: Add Synced Labels
    steps:
      - uses: actions/checkout@v2
        name: Checkout
      - uses: Resnovas/label-mastermind@2.1.3
        name: Labeling
        with:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN  }}'
  Add_Other_Labels:
    runs-on: ubuntu-latest

    steps:
    - name: Add_Other_Labels
      id: labeler
      uses: jimschubert/labeler-action@v1
      with:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

  Add_To_Project:
    runs-on: ubuntu-latest
    steps:
      - run: |
          PROD=$(echo "${{ github.event.issue.body }}" | egrep -i 'Product[^#]*')
          echo "product=$PROD" >> $GITHUB_ENV
      - run: |
          echo "This is product ${{ env.product }}"
      - uses: alex-page/github-project-automation-plus@v0.8.1
        if: ${{ contains(env.product, 'Shop' ) }}
        with:
          project: vvvvv
          column: Triage
          repo-token: '${{ secrets.OPT_GH_TOKEN }}'

