name: Setup new Issues

on:
  issues:
    types: [opened]

jobs:

########
## Check if the issue should be transfered to another repo
########
  transfer_issue:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - regexp: '/Product[^\w\r\n]*POMA/im'
            repo: testRepo
          - regexp: '/Product[^\w\r\n]*shop/im'
            repo: testRepo
    steps:
    - name: Transfer Issue & Comment
      uses: christofferDahlen/transfer-issue-action@v3
      id: transfer-issue
      with:
        target_repo: ${{ matrix.repo }}
        token: '${{ secrets.OPT_GH_TOKEN }}'
        req_regexp_match: ${{ matrix.regexp }}
        debug: true
        create_stub: true
    - run: |
        echo "${{ steps.transfer-issue.outputs.destination_repo }}"
    - name: Set transfer status
      if: steps.transfer-issue.outputs.destination_repo != ''
      run: |
        echo "::set-output name=remain::true"

########
## Check if the title is correct 
########

  check_title:
    needs: transfer_issue
    if: needs.transfer_issue.output.remain == 'true'
    runs-on: ubuntu-latest
    steps:

      - uses: actions-ecosystem/action-regex-match@v2
        id: regex-match
        with:
          text: ${{ github.event.issue.title }}
          regex: '^(\[[^\]]*\]:?\s?(title)?)?$'
          flags: gm
      - uses: actions-ecosystem/action-create-comment@v1
        if: ${{ steps.regex-match.outputs.match != '' }}
        with:
          github_token: ${{ secrets.github_token }}
          body: |
            Seems like you have forgotten to fill out the title of issue. Please fill it in properly.

            If this is wrong just ignore this comment

########
## Adding other labels
########
  Add_Other_Labels:
    needs: [transfer_issue, check_title]
    if: needs.transfer_issue.output.remain == 'true'
    runs-on: ubuntu-latest
    steps:
    - name: Add_Other_Labels
      id: labeler
      uses: jimschubert/labeler-action@v1
      with:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

########
## Add the sync labels
########

  Add_Synced_Labels:
    needs: [transfer_issue, check_title]
    if: needs.transfer_issue.output.remain == 'true'
    runs-on: ubuntu-latest
    name: Add Synced Labels
    steps:
      - uses: actions/checkout@v2
        name: Checkout
      - uses: Resnovas/label-mastermind@2.1.3
        name: Labeling
        with:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN  }}'

########
## Add issue to the appropriate 
########

  Add_To_Project:
    needs: [transfer_issue, check_title]
    if: needs.transfer_issue.output.remain == 'true'
    runs-on: ubuntu-latest
    steps: 
    - name: Get Product Name
      run: |
        echo "::set-output name=name::$(echo "${{ github.event.issue.body }}" | grep -oe 'Product: .*' | tr '[:upper:]' '[:lower:]')"
      id: product

    - uses: alex-page/github-project-automation-plus@v0.8.1
      if: ${{ contains( steps.product.outputs.name, 'shop' ) }}
      with:
        project: Connecting Shop Board 
        column: Triage
        repo-token: '${{ secrets.OPT_GH_TOKEN }}'

    - uses: alex-page/github-project-automation-plus@v0.8.1
      if: ${{ !contains( steps.product.outputs.name, 'shop' ) }}
      with:
        project: Optimisation Core Board
        column: Triage
        repo-token: '${{ secrets.OPT_GH_TOKEN }}'



