  name: pending-author-response
  on:
    issue_comment:
      types: [created]

  jobs:
    issue_commented:
      if: ${{ !github.event.issue.pull_request  && contains(github.event.issue.labels.*.name, '[X] :basketball:') }}
      runs-on: ubuntu-latest
      steps:
        - uses: siegerts/pending-author-response@v1
          with:
            github-token: ${{ secrets.GITHUB_TOKEN }}
            pending-response-label: "[X] :mailbox:"
            actionable-label: "[X] :basketball:"