name: AssignReviewers
on:
  pull_request:
    types: [assigned, unassigned]

jobs:
  assignee_to_reviewer:
    runs-on: ubuntu-latest
    name: Assignee to Reviewer
    steps:    
      - uses: abinoda/assignee-to-reviewer-action@v1.0.4
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'

