on:
  issues:
    types:
      - labeled



jobs:
  transfer_issue:
    name: Tranfser issue
    runs-on: ubuntu-latest
    steps:
    - name: Match body
      id: match
      uses: ChristofferDahlen/Multi-Regex-Match@v1.0
      with:
        input: "${{ github.event.issue.body }}"
        json_match: '{ 
          "testRepo" : "/Product[^\\w\\r\\n]*POMA/im"
        }'
    - run: |
          if [ "${{ steps.match.outputs.result }}" == "" ]; then
            echo ::set-output name=remain::false
          else
            echo ::set-output name=remain::true
          fi
      id: state

    - name: Transfer Issue & Comment
      if: steps.state.outputs.remain != 'false'
      uses: christofferDahlen/transfer-issue-action@v3
      with:
        target_repo: ${{ steps.match.outputs.result }}
        token: '${{ secrets.OPT_GH_TOKEN }}'
        debug: true
        create_stub: true
